sudo: required
services:
  - docker

before_install:
  - docker build -t titanxl/docker-react-app -f Dockerfile.dev .

script:
  - docker run titanxl/docker-react-app npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: docker-react
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-810433389795"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
